### ISSUE TITLE
dnSpyEx 6.4.1 crash

### ISSUE THREAD

**Issue by greenozon** [dnSpyEx/dnSpy#249] opened 2023-10-02 10:21 UTC
### dnSpyEx version

dnSpy v6.4.1 (.NET Framework)  (latest vanilla build)

### Describe the Bug

Attach to process,
Pause
then open module from memory
it shows crash dialog
then dnSpyEx silent dies

### How To Reproduce

see above

### Expected Behavior

successfull attach

### Actual Behavior

crash

### Additional Context

it shows following error window on an attempt of the steps above:

![image](https://github.com/dnSpyEx/dnSpy/assets/765343/0b770fff-e7be-4eee-a1a5-51fdbf5b46f3)

**Comment by ElektroKill** [comment] 2023-10-02 17:34
Hi, please provide the file you are working with so that I can reproduce the crash. I cannot seem to reproduce the issue with my own test files. If you do not feel comfortable uploading the file to GitHub, you can email it to me at elektrokilldev@protonmail.com.

Thanks in advance!

**Comment by greenozon** [comment] 2023-10-02 19:04
sent out by email
thanks!

**Comment by ElektroKill** [comment] 2023-10-07 11:21
Hi, the reason for the crash is that dnSpy is unable to retrieve the module metadata from both memory and from the debugger APIs. This is a direct result of the anti-dump protection found in the target file being run before the debugger is attached. The anti-dump protection purposefully "corrupts" the in-memory metadata in such a way that the runtime can still execute the file but tolls like dnSpy and the CorDebug API have trouble reading the metadata. The best thing I can do in this case is to implement some logic to avoid the crash when the metadata cannot be read. This would make the open module from memory do nothing in this case. The only way to load the module properly would be to disable the anti-debug routine or attach the debugger before it is executed.

**Comment by greenozon** [comment] 2023-10-07 12:38
Thank you for the detailed feedback
it was kind of expected, so lets make what is needed in order to not crash the tool!
also maybe would be good to show some warning box to the user to let him know that this kind of crazy stuff has happened  (the war just began)
:)

**Comment by ElektroKill** [comment] 2023-10-11 17:38
Hi, I went ahead and implemented graceful handling for scenarios where the `IMetaDataImport` interface is not available. After these changes, clicking Open module from memory will result in nothing happening as the in-memory metadata is not valid. I will work on implementing cod to display an error dialog in the coming days!

You can test it for yourself by using the build from here: https://github.com/dnSpyEx/dnSpy/actions/runs/6486051098 (had to manually run the workflow for some reason, not sure why GitHub skipped the automatic run!)

**Comment by greenozon** [comment] 2023-10-11 19:06
Thanks! gave it a test try - everything is behaving  as you desribed above!

**Comment by ElektroKill** [comment] 2023-10-12 18:29
I have added the aforementioned error dialog. A build featuring this change is available here: https://github.com/dnSpyEx/dnSpy/actions/runs/6499525287

**Comment by greenozon** [comment] 2023-10-12 19:08
Nice!
just gave it a try:
![image](https://github.com/dnSpyEx/dnSpy/assets/765343/f72803c7-5585-446c-b6bb-c0fafd5529cd)

**Comment by ElektroKill** [comment] 2023-10-13 07:12
Good to hear that, I will close the issue now as there is not much more that can be done to improve the behavior of dnSpy in cases when the metadata cannot be accessed!

**Closed by ElektroKill** 2023-10-13 07:12 UTC
Labels: bug, debugger
