### ISSUE TITLE
.NET 6.0 Crash on Click View in Menu

### ISSUE THREAD

**Issue by Deltafox79** [dnSpyEx/dnSpy#58] opened 2021-12-19 09:34 UTC
Before clicking `Submit new issue`, try the latest build [![](https://github.com/dnSpyEx/dnSpy/workflows/GitHub%20CI/badge.svg)](https://github.com/dnSpyEx/dnSpy/actions)

- What version did you use?
Latest 6.1.9 Compiled at 19 December 2021 .NET 6.0

- Write down all steps needed to reproduce this issue. Also attach any needed files.

![Senza titolo](https://user-images.githubusercontent.com/2518850/146670184-6864f585-360c-4e2f-8e24-8cd931c1b9c8.jpg)

After compiling the .NET 6.0 version the **Microsoft.CodeAnalysis.Scripting** library is missing

Regards

**Comment by ElektroKill** [comment] 2021-12-19 09:54
Hi, I experience this issue myself in development too. For some reason, the dnSpy project is set up in such a way that the .NET version only works properly when being published. The problem is that when building the some of the NuGet dependencies are not copied to the output folder. Apparently, this should be fixed by setting the `CopyLocalLockFileAssemblies` property in the project file but what's strange is that dnSpy already sets it here and it doesn't make MSBuild copy all the files... https://github.com/dnSpyEx/dnSpy/blob/623956ecbffdfa156655e12fddefc4556a9391e9/DnSpyCommon.props#L21

I'm yet to find a fix for this problem.

**Closed** 2023-01-21 10:20 UTC
Labels: bug
