### ISSUE TITLE
[Feature request] Opening .NET host executables

### ISSUE THREAD

**Issue by PercyDan54** [dnSpyEx/dnSpy#179] opened 2023-03-05 02:55 UTC
Before clicking `Submit new issue`, try the latest build [![](https://github.com/dnSpyEx/dnSpy/workflows/GitHub%20CI/badge.svg)](https://github.com/dnSpyEx/dnSpy/actions)

- What version did you use?
v6.3.0

- Write down all steps needed to reproduce this issue. Also attach any needed files.

Recently I've tried JetBrains dotPeek and found a feature I'd like to see in dnSpy (it's not present in ILSpy either).

When you open a .NET host executable dnSpy just shows basic PE info, as if it's a non-.NET executable. But dotPeek shows the related assembly like this

![image](https://user-images.githubusercontent.com/50285552/222939141-0b2085a6-28b2-4be4-987e-618236f67336.png)

**Comment by ElektroKill** [comment] 2023-03-05 11:02
Duplicate of #16

**Closed by ElektroKill** 2023-03-05 11:02 UTC

**Comment by PercyDan54** [comment] 2023-03-05 11:05
> Duplicate of #16
> 
> Support for these files is a planned feature.

I don't think this is a duplicate. The said executable is not a single file

**Comment by ElektroKill** [comment] 2023-03-05 11:10
Oh my bad, the file you are looking at is just an apphost and not a bundle. `Lyrics.exe` is just bootstrap exe which runs the code in `Lyrics.dll`. The `Lyrics.exe` file does nothing else but that. If you want to analyze this application just open `Lyrics.dll` like you would any other file. During debugging, dnSpy will locate the correct apphost to use to start the executable. 

dotPeek just automatically loads the `.dll` when you load the `.exe`. Something dnSpy does not do as a means to make the distinction of what information is actually present in a file.
