### ISSUE TITLE
Decompiler should respect inheritance 

### ISSUE THREAD

**Issue by gir489returns** [dnSpyEx/dnSpy#200] opened 2023-05-24 21:57 UTC
### Problem Description

When decompiling a function for a class that's a child, if that function calls another function the child overwrites, dnSpy will show you the parent's function (most of the time a stub function) and not the child's function. Law of inheritance for OOP, if you call a function, the most recently inherited function is called.

Here is an example in Valheim.

UpdatePlacement is a function of Player. Player extends Character. Inside UpdatePlacement, HaveStamina is called. When you click on or get information for HaveStamina, it shows you Character::HaveStamina, but Player overrides HaveStamina with its own function.

![image](https://github.com/dnSpyEx/dnSpy/assets/100792176/fd8d7d14-33e5-4c32-9453-a06f8b2e79d4)
![image](https://github.com/dnSpyEx/dnSpy/assets/100792176/a5987601-5001-434a-97bb-66323eaab898)
![image](https://github.com/dnSpyEx/dnSpy/assets/100792176/f9db922e-87bc-4403-9a21-4bd937bec896)

### Proposal

The decompiler should check if the child class contains an override function, and if it does, it should use that instead of the parent function. ilSpy does this already.

**Comment by ElektroKill** [comment] 2023-05-25 18:00
Hi,

this is because dnSpy by design navigates to the raw member references found in the metadata/method body. Calls to virtual methods are compiled to a `callvirt` instruction with an operand that references the base member. The resolution of the correct overload is performed by the .NET runtime during program execution. The reason why dnSpy is designed to navigate to the raw metadata reference is that at CIL/.NET metadata level we cannot be sure how the VTable will look like at runtime for a given base method.

For example:
Consider the following classes:
`Class1` - a base class that contains a virtual method called `VirtualMethod`.
`Class2` - a class that derives from `Class1` and overrides `VirtualMethod` with its own implementation.
`Class3` - a class that derives from `Class2` and overrides `VirtualMethod` with its own implementation.
Now consider the following method:
```c#
void MyMethod(Class2 class2) {
	class2.VirtualMethod();
}
```

When compiled, the body of `MyMethod` contains a `callvirt` instruction that references `Class1.VirtualMethod`. If you click on the call in decompiled code in dnSpy that is where it will jump to. 

See https://sharplab.io/#v2:EYLgtghglgdgNAFxFANgHwAICYCMBYAKAwGYACbUgYRQgGdadSBvQ0t8sgNygCcEBXCCnIAWUgDVeAoQFkApggAWAewAmACgCUzVuwC+hAwUIlyWKjXrmQFugx0F2HUss5yePKKrmiJUwSjySmpaDk5GRiZkFNR2ZDaxVmHspq7unt6+knwBQSoa2iyO+oaEZUTROABsZqQAyggQCFAAxom0yWymGNW+MgCeeSHt5i2WtFiaRU5OY3ZYAHTZ0oEK+VoA3LpsEUA=

In this situation, it is impossible to determine which `VirtualMethod` implementations will be called. `MyMethod` could be called with an instance of `Class2` or `Class3` and we do not know which one it will be at decompile time. I'm pretty sure ILSpy will just try to guess the override that will be called. However, I believe that trying to guess the right override here is less clear and understandable than just jumping to the base implementation from which the user can use the analyze option to find all possible implementations of it that could be called.

I hope this explanation makes the decision to navigate to the actual metadata member more understandable :p
If you have any more questions regarding this feel free to ask :D

**Comment by ElektroKill** [comment] 2023-07-08 19:49
Closing as a won't fix. The behavior mentioned will not be changed for the aforementioned reasons!

**Closed by ElektroKill** 2023-07-08 19:49 UTC
Labels: enhancement, decompiler
