### ISSUE TITLE
Crash after "Edit Class" -> "Compile"

### ISSUE THREAD

**Issue by FickoDeLux** [dnSpyEx/dnSpy#165] opened 2023-01-30 12:51 UTC
Ver. 6.3.0

After opening "Edit Class" and closing (with or without editing anything) with "Compile" i am getting exceptions.

It does not happen with Ver. 6.2.0 using the same source.

It seem's that the compilation does take place but it crashes somewhere by displaying the result.

![Exception](https://user-images.githubusercontent.com/19427606/215481054-5534e7c2-9b86-4ef3-b2e6-53fe97373a67.jpg)

**Comment by sunnamed434** [comment] 2023-01-30 12:54
Can you please attach the used file in dnSpy?

**Comment by FickoDeLux** [comment] 2023-01-30 14:52
Attached.
The "namespace MSAppNS.AppMode" "public class ApplicationMod", which I tryed to recompile.
[commonDotNet.zip](https://github.com/dnSpyEx/dnSpy/files/10536850/commonDotNet.zip)

**Comment by sunnamed434** [comment] 2023-01-30 19:10
I'm unable to compile it because I don't have libraries, would be great if you share them. Which dnSpy build do you use? (win32, win64, net framework) - you can find it [here](https://github.com/dnSpyEx/dnSpy/releases/tag/v6.3.0), and search for `Assets`, I've used v6.3.0 net-framework

**Comment by FickoDeLux** [comment] 2023-01-31 09:22
I just tryed net-win64 as well. (v6.3.0)
Compiling the entire "ApplicationMod" class seems to work.
But if I change anything like "return this.isPremium;" to return true;
Getting the attached exceptions.:
![Exception-net-win64](https://user-images.githubusercontent.com/19427606/215719058-a5d8ae96-7b37-4026-82f2-c8eaa96a13ac.jpg)

Ver 6.2.0 works fine.

**Comment by sunnamed434** [comment] 2023-01-31 10:06
> Sorry I should know one dll will be not enough. I am using net framework.
> 
> Attached the minimum dependencies I was able to compile (reproduce the exception) the above mentioned class. [MinDepend.zip](https://github.com/dnSpyEx/dnSpy/files/10544560/MinDepend.zip)

Thanks for the references. I'm getting the same problem, how to reproduce:
1. Find `MSAppNS.AppMode.ApplicationMod` in search of dnSpy
2. Click the right mouse on `ApplicationMode` class 
3. Press `Edit Class (C#)...`
4. Add something in the ctor of `ApplicationMode`, for example, `Console.WriteLine("Hello world")`
5. Press compile
6. Reproduced, getting an exception, @FickoDeLux, perhaps you're right, this is a bug of dnSpy

## Workaround
This is very interesting that after the exception you can close it, check the IL code editor and see that your code was successfully added to the ctor, but not to the view, so, just ignore the error and easily compile it and then build (very important to Press `X` on top-right, to not allow the dnSpy to be crashed)
As a temp solution if you really need to change there something, use the IL code editor

As you can see in the screenshots there's a difference between them but the view stays as it was before.
![image](https://user-images.githubusercontent.com/65300126/215728934-e124c62a-177c-44b3-ac5c-5f14d70539df.png)
![image](https://user-images.githubusercontent.com/65300126/215728841-fa3d0d16-e4e6-4717-bc4c-2da91b53dbe5.png)

Successfully build, see `MSAppNS.AppMode.ApplicationMod`, I added Console.WriteLine with hello world
[commonDotNet123.zip](https://github.com/dnSpyEx/dnSpy/files/10545230/commonDotNet123.zip)

**Closed** 2023-02-04 17:32 UTC
