### ISSUE TITLE
Debug IIS process .NET 6

### ISSUE THREAD

**Issue by florin30** [dnSpyEx/dnSpy#96] opened 2022-06-27 13:36 UTC
It seems that it is not possible to debug a (web) app that is hosted in IIS and runs on .NET 6.
I have tried older versions and the latest ones and it doesn't work. If the application was running on .NET 5, you can debug it.

What I do is: attach to IIS process with dnSpy, open the module where I want to debug, set a breakpoint and then access a URL.
What happens: the process hangs, not breakpoint hit. Event without setting a breakpoint, the process still hangs.
There might be some issue with the debugger and .NET 6 when the process is hosted by IIS.

If I start the same application without IIS, everything works fine, breakpoint hits.

I can debug the process in IIS with WinDbg or VS, but with dnSpy it hangs and nothing happens. If I stop debugging, the application resumes and continues.
If I suspend the application and switch to Threads tab, nothing is shown.

**Comment by josegomez** [comment] 2022-07-27 21:10
I can confirm this issue, same thing happens to me. Debugging any inprocess or out of process web app causes the web app to hang (as if it was paused) and does not resume until you detach the debugger.

**Comment by josegomez** [comment] 2022-07-27 21:21
Here's a quick demo of the issue if it helps, it doesn't appear that it needs to be an IIS hosted App this was happening when I ran the app from command line 
https://youtu.be/PXGb0eWdgu8

Though I see that @florin30 said it worked fine for them outside IIS. How did you execute the app in a way that it worked @florin30 ?

**Comment by ElektroKill** [comment] 2022-07-28 18:18
Hi, after some investigating this issue I was able to narrow it down to the `Anonymously Hosted DynamicMethods Assembly` assembly which is created by the runtime and is a dynamic module. If I attach dnSpy in debug mode to the process before this module is created, everything works as usual and no assertions are hit. However, if dnSpy is attached after this assembly is created, during attachment, an assertion is immediately hit and several other debugger actions lead to assertions. I will continue my investigation into this bug and keep this issue updated with my findings.

**Comment by ElektroKill** [comment] 2022-07-28 19:04
Update: I have identified the root cause of the issue to be the `ICorDebugModule::GetMetaDataInterface` function. When attaching after the `Anonymously Hosted DynamicMethods Assembly` assembly is created, this function fails to retrieve a metadata interface. If the assembly is created with the debugger attached the function succeeds. This causes exceptions which later lead to the process remaining in the suspended state. This means the problem is not specific to either IIS or web apps. Anything that causes the runtime to create the aforementioned assembly will cause this error.

Why does the process remain in the suspended state? When the dnSpy debugger receives the LoadModule event for the module inside `Anonymously Hosted DynamicMethods Assembly`, an exception is thrown here:
https://github.com/dnSpyEx/dnSpy/blob/6b00a1c4d65555ba31f66cefe164c2028cf5e765/Extensions/dnSpy.Debugger/dnSpy.Debugger.DotNet.CorDebug/Impl/ModuleCreator.cs#L94-L96
This exception then makes its way up to the exception handler found in the following method:
https://github.com/dnSpyEx/dnSpy/blob/6b00a1c4d65555ba31f66cefe164c2028cf5e765/Extensions/dnSpy.Debugger/dnSpy.Debugger.DotNet.CorDebug/dndbg/Engine/DnDebugger.cs#L304-L336
The reception is caught, the debugger state is reset and the exception is rethrown. The problem is caused by the fact that the rethrow causes this code to be skipped:
https://github.com/dnSpyEx/dnSpy/blob/6b00a1c4d65555ba31f66cefe164c2028cf5e765/Extensions/dnSpy.Debugger/dnSpy.Debugger.DotNet.CorDebug/dndbg/Engine/DnDebugger.cs#L324-L335
Can you guess what this code does? If your guess was something along the lines of it resumes execution then you would be right. Due to the fact that this is skipped the process remains in this "limbo" state and acts as if it was frozen until the debugger is detached.

Now that the cause of the issue was identified, I moved on to trying to figure out why it worked in previous runtimes. Luckily, I didn't have to look for long! It turns out this is a bug in the .NET runtime itself and has been reported since December! 
Link to runtime issue: https://github.com/dotnet/runtime/issues/62977
Looks like this problem will be fixed properly in .NET 7. I'm not sure if the .NET team will backport this fix into .NET 6.0 or not. If they don't this will have to be fixed on dnSpy's side with what would probably be a dirty and hacky fix.

**Comment by josegomez** [comment] 2022-07-28 19:19
Thanks @ElektroKill ! We did some debugging yesterday and landed in that same GetMetaDataInterface call but couldn't figure out from there.
Is there a quick and dirty work around we could do like catching a specific exception and basically doing a "try catch shush" to get around it temporarely?

**Comment by cloud9tn** [comment] 2022-07-28 19:23
As part of the dead weight reviewing this with @josegomez  last night, I'd also like to extend thanks to you @ElektroKill .

**Comment by florin30** [comment] 2022-07-28 19:23
@josegomez you are right, it does not work if I start the web app from cmd.
I had a Sleep in Main, before calling the WebApplication's Run method. If I attached to the process before the Sleep ran out, it worked. If I attach after Run was executed, it doesn't work.

@ElektroKill ok, I understand now the issue. I just checked in .NET 5 and there is no "Anonymously Hosted DynamicMethods Assembly" created, that's why it works. Great findings you did there for this issue :D

So, as a workaround we would have to create some Sleeps or find a way to attach the debugger before that Assembly is created.
Do you think an "unofficial" build can be made with a hacky fix for this? Or is it not worth the effort?

In the meanwhile, I will try to find some time to investigate it a bit and try find a temporary fix, which we could include to create such a build to support these applications, if you like.

Maybe we could determine if `dnModule.CorModule` is "Anonymously Hosted DynamicMethods Assembly", then throw a different error, and we add a special handling case for it to resume the debugger?

**Comment by ElektroKill** [comment] 2022-07-28 19:36
> Maybe we could determine if `dnModule.CorModule` is "Anonymously Hosted DynamicMethods Assembly", then throw a different error, and we add a special handling case for it to resume the debugger, or ignore the error completely?

Checking by name will not work, this issue affects all dynamic modules, not only the ones used by `DynamicMethod` objects. The best "fix" or rather a hack I found for this would be to check if `dnModule.Process.CorProcess.CLRVersion.Major` is equal to 6, effectively checking if the runtime is .NET 6 and instead of throwing an error, return a new implementation of `DmdLazyMetadataBytes` which contains no information and has a special case in `DmdAppDomainImpl.CreateMetadataReader` to create a `DmdNullMetadataReader`. This would effectively treat the module as if it had no metadata. The exception is there since under normal bug-free circumstances dynamic modules should always provide a metadata interface.

**Comment by hasokeric** [comment] 2022-07-28 20:15
Good to know that I am not crazy. Kudos and good find. Same struggle here.

**Comment by josegomez** [comment] 2022-07-28 20:49
PR for the Issue tested it and it works for me, thanks for the thorough explanation @ElektroKill . I don't expect you to merge this, just threw it out here for others having the same issue.

Thanks a ton!

**Comment by josegomez** [comment] 2022-07-29 01:50
![DNSPY](https://user-images.githubusercontent.com/420837/181666044-74bc8808-7778-4f2f-bfbb-cec487f0f4ec.gif)
 Success! With the most complex app I have its an ERP System written fully in NET 6 running on IIS out of process works like a dream

**Comment by ElektroKill** [comment] 2022-07-29 11:48
A workaround for the .NET 6 bug has been implemented in https://github.com/dnSpyEx/dnSpy/commit/02623aa4e413c5faa88b2fdde66ce9268b646b99

**Closed by ElektroKill** 2022-07-29 11:48 UTC
Labels: bug, debugger

**Comment by hasokeric** [comment] 2022-08-02 14:36
Awesomesauce there you go @florin30
