### ISSUE TITLE
Can't attach to .NET 5 application

### ISSUE THREAD

**Issue by greenozon** [dnSpyEx/dnSpy#48] opened 2021-11-14 12:31 UTC
- What version did you use?
dnSpy v6.1.9 

- Write down all steps needed to reproduce this issue. Also attach any needed files.

When trying to attach I see this error box:

![image](https://user-images.githubusercontent.com/765343/141681231-1cc4b4ae-c2cd-4350-b8a3-fd8928ad4711.png)

![image](https://user-images.githubusercontent.com/765343/141681105-815bdb13-89dd-4fd4-b520-e46b94f58355.png)

dlls having this attribute:

[assembly: TargetFramework(".NETCoreApp,Version=v5.0", FrameworkDisplayName = "")]

**Comment by ElektroKill** [comment] 2021-11-14 12:52
Hi, could you please provide a file that I can use to reproduce this issue?

**Comment by greenozon** [comment] 2021-11-14 13:36
How could I send you the stuff privately?

**Comment by ElektroKill** [comment] 2021-11-19 17:27
You can send the sample to the following email address:
`dnspy.ex@gmail.com`

**Comment by greenozon** [comment] 2021-11-19 19:50
Thanks
Sent

**Comment by GazziFX** [comment] 2021-11-29 09:19
Did you try to use master version instead of 6.1.9? because release based on old libraries

**Comment by greenozon** [comment] 2021-11-29 09:29
Nope, I used only rls version
THanks for nice hint, I"ll give it a try

**Comment by greenozon** [comment] 2021-11-29 10:26
Just built all the stuff from master branch (used dotnet build + VS2019)

ran x64 exe for .NET Framework and got the same error as before

![image](https://user-images.githubusercontent.com/765343/143850949-5b6e2faf-0e5a-4a85-b05c-2af79e63f28e.png)

but debug version also shown some Assert window after this error box:

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------

   at dnSpy.MainApp.AppStatusBar.Show(String text) in C:\denSypEX_src\dnSpy\dnSpy\dnSpy\MainApp\AppStatusBar.cs:line 60
   at dnSpy.Debugger.DbgUI.DebuggerImpl.SetStatusMessage_UI(String message) in C:\\denSypEX_src\dnSpy\Extensions\dnSpy.Debugger\dnSpy.Debugger\DbgUI\DebuggerImpl.cs:line 499
............
```

**Comment by greenozon** [comment] 2021-11-29 10:29
Addon:  running net5.0-windows\dnSpy.exe  produces some error box and does not start at all

question: is .NET 5 is a supported platform to build dnSpyEx against?

**Comment by GazziFX** [comment] 2021-11-29 10:33
> Addon: running net5.0-windows\dnSpy.exe produces some error box and does not start at all
> 
> question: is .NET 5 is a supported platform to build dnSpyEx against?

I build with `build.ps1` and run binaries from publish folder, it works on net5.0

**Comment by greenozon** [comment] 2021-11-29 10:35
how do you use that ps1 file?
I'm not able to execute it under W7 x64...

**Comment by GazziFX** [comment] 2021-11-29 10:39
> how do you use that ps1 file? I'm not able to execute it under W7 x64...

First allow PowerShell scripts execution, then open project in VS, right click on solution > open terminal > type `./build.ps1 -NoMsbuild` without `-NoMsbuild` also should work

**Comment by ElektroKill** [comment] 2021-11-29 16:59
Please use the file in the publish folder. Alternatively you can use the builds provided and created automatically by GitHub actions.

**Comment by greenozon** [comment] 2021-11-29 17:17
Gave it a try - ran \dnSpy\dnSpy\dnSpy\bin\Release\net5.0-windows\win-x64\publish\dnSpy.exe 

it shows same error on attach attempt

![image](https://user-images.githubusercontent.com/765343/143912911-f0ce810f-17ca-4d9d-b0ae-56a725def565.png)

**Comment by greenozon** [comment] 2021-11-29 17:18
Also, when I tried to run dnSpy from this location
\dnSpy\dnSpy\dnSpy\bin\Debug\net5.0-windows\dnSpy.exe 

 it said

![image](https://user-images.githubusercontent.com/765343/143913335-d5ffc31c-8355-4d33-aa96-d745a7f003cf.png)

was that expected?
of course I"ve installed .NET5 on my PC

**Comment by greenozon** [comment] 2021-11-29 17:35
./build.ps1  after building of bits produces size of dir like **13 GB** (wow!??!)

**Comment by ElektroKill** [comment] 2021-11-29 18:44
Hi, it seems like `dbgshim!CreateDebuggingInterfaceFromVersionEx` which is called by dnSpy to get a `ICorDebug` instance is failing when trying to debug the sample you provided. It returns the following HRESULT: `0x80131C3C` and the object returned is null. I am yet to identify the root cause of this call failing but I will keep looking :)

**Comment by greenozon** [comment] 2021-11-29 19:39
wow, I've gathered some facts about huge size of build

I've explored the built dir and you know what? it created for some unkown reason dozens of same dir, eg:

dnSpy\dnSpy\dnSpy\bin\Release\net5.0-windows\win-x86\publish\bin\bin\bin\bin\bin\bin\bin\bin

each bin dir has a FULL copy of dozens of dlls + exe  (full dnSpy distribution)

I guess thats definitely not good

**Comment by greenozon** [comment] 2021-11-29 19:55
@ElektroKill 
as .net is public & opencourse, maybe reading the failed API code would help to understand the issue?

eg  https://github.com/dotnet/runtime/blob/39b4f2661f7ea5abbffcb1cb15e78363af9a81c7/src/coreclr/dlls/dbgshim/dbgshim.cpp#L1882

**Comment by InKahootz** [comment] 2021-12-07 15:59
> wow, I've gathered some facts about huge size of build
> 
> I've explored the built dir and you know what? it created for some unkown reason dozens of same dir, eg:
> 
> dnSpy\dnSpy\dnSpy\bin\Release\net5.0-windows\win-x86\publish\bin\bin\bin\bin\bin\bin\bin\bin
> 
> each bin dir has a FULL copy of dozens of dlls + exe (full dnSpy distribution)
> 
> I guess thats definitely not good

This is expected when multi-targeting frameworks, especially when you have many libraries like dnSpy.

`bin\Release\net48` will have a copy of the .NETFramework assemblies
`bin\Release\net5.0-windows` is the non-published .NET assemblies
`bin\Release\net5.0-windows\[win-x86|win-x64]` is architecture specific .NET
`bin\Release\net5.0-windows\[win-x86|win-x64]\publish` is the final .NET publishing output

**Comment by greenozon** [comment] 2021-12-07 21:46
@InKahootz  I agree wiht your statement that each type of build will have accompanying .net files
but what about bin\bin\bin\bin\bin\bin\bin\bin\bin\bin\bin\bin\bin\bin\  issue?

**Comment by ElektroKill** [comment] 2021-12-08 05:46
> but what about bin\bin\bin\bin\bin\bin\bin\bin\bin\bin\bin\bin\bin\bin\ issue?
> please note that each bin has a full set of .net files - definitely smth wrong over there
I haven’t encountered such issue on my system. I think there most be something wrong on your end maybe?

**Comment by greenozon** [comment] 2021-12-08 06:59
Yeah, makes sense
I need to dig deeper into that issue...
might be some corner case

**Comment by greenozon** [comment] 2022-06-15 17:51
bumping up old issue
just tried out on brand new release 6.2.0 - same error (can't attach)

**Comment by ElektroKill** [comment] 2022-11-26 12:45
Hi, I did some research and I think this may be caused by the fact that the file you are trying to debug is a self-contained executable published in release mode. 

If you want to debug this file, I recommend "converting" this file into a non-self-contained .NET program. Here is how you can do so:
1. Run the app without attaching any sort of debugger:
![image](https://user-images.githubusercontent.com/37494960/204088304-b3c9b701-afde-4b29-8a37-6047308548e0.png)
2. Navigate to `%temp%`. This can be done, for example, by pressing `Win + R` on the keyboard, typing `%temp%` and clicking Ok, or hitting the enter key on the keyboard.
![image](https://user-images.githubusercontent.com/37494960/204088435-e165314f-d355-4707-86d3-6eef70b1daf4.png)
3. Locate the `.net` folder and enter it.
![image](https://user-images.githubusercontent.com/37494960/204088496-cfa2e2d9-aa00-4bc9-ad1b-238e8c04feb3.png)
4. Find the folder corresponding to the name of the app you are trying to convert. In this case `TickStrikeAlpha` and enter it
![image](https://user-images.githubusercontent.com/37494960/204088540-0b2c7af7-9981-420e-b1f4-a30a5e12e18b.png)
5. Now we want to copy the folder which has a name composed of random characters to a different location. In this scenario, I will copy it to my desktop and rename it to `TickStrikeAlpha-converted`
![image](https://user-images.githubusercontent.com/37494960/204088584-b9e37a18-8947-4485-a8f9-8a064abba124.png)
![image](https://user-images.githubusercontent.com/37494960/204088594-1dedf6a7-24a9-489a-b3c4-2a51d19b8e67.png)
![image](https://user-images.githubusercontent.com/37494960/204088618-34e5034c-d494-4b9a-8557-bbd85f429d1a.png)
6. At this point it is okay to close the original app, we don't need it anymore.
7. We open the newly copied folder and dig through the many `.dll` files to locate a file named `{applicationName}.runtimeconfig.json` (for this scenario it's called `TickStrikeAlpha.runtimeconfig.json`).
![image](https://user-images.githubusercontent.com/37494960/204088704-64fc2a44-45f3-4b48-93ff-81e8cbeb7e6b.png)
8. Open this text file in any text editor of your choice (I'm using Notepad++). It should look something like this (version numbers may differ): 
![image](https://user-images.githubusercontent.com/37494960/204088771-8ccfee8e-e2b2-4ca1-819e-fdecf5874a47.png)
9. Locate the `includedFrameworks` string, then change it to `frameworks` and save the file. The result should look like this:
![image](https://user-images.githubusercontent.com/37494960/204088841-14a52956-a9c5-4142-8c9a-88be3f56e533.png)
10. Now find a file named `{applicationName}.deps.json` (in this case `TickStrikeAlpha.deps.json`) in the same folder as the previous file we edited and open it in your text editor of choice.
![image](https://user-images.githubusercontent.com/37494960/204089289-902fa14b-e4e4-44de-96b9-9733e71f7acb.png) Now locate the following text (version numbers may differ, the number of runtime packs and their names may differ too) 
![image](https://user-images.githubusercontent.com/37494960/204089341-2b72483b-67c8-46da-9991-fddb648a4f5d.png) Go ahead and delete the runtime pack entries and save the file. The result should look like this 
![image](https://user-images.githubusercontent.com/37494960/204089406-831326c1-c3ba-4691-9ea5-edb92bce2181.png)

and we are done! The program is now converted into a normal .NET application which can be easily debugged and executed.
* If you want to execute this converted program, open the command prompt, navigate to the current folder and run the `dotnet {applicationName}.dll` command (in this scenario it would be `dotnet TickStrikeAlpha.dll`). Make sure you have the correct .NET runtime installed! 
![image](https://user-images.githubusercontent.com/37494960/204089018-f92f5794-d8e0-468c-8b5f-c34ff4f61a6b.png)
* If you want to debug the file, open `{applicationName}.dll` (in this case `TickStrikeAlpha.dll`) in dnSpy and click the Debug button. dnSpy should suggest the following start options: 
![image](https://user-images.githubusercontent.com/37494960/204089107-ee942579-da8e-46c2-be44-ae6338ee3f85.png) Just click OK and the debugging will commence!
![image](https://user-images.githubusercontent.com/37494960/204089536-bdc8ab04-079f-4fa0-a6f4-a539157b004e.png)

Hope this guide helps!

I will try to do more research as to why debugging these self-contained files published in release mode does not work. (I have a suspicious that maybe the release mode self-contained runtime does not support debugging 🤔)

If you have any questions relating to this please go ahead and ask them :P

**Comment by jogibear9988** [comment] 2022-11-26 16:21
https://github.com/dotnet/runtime/issues/42927

**Comment by ElektroKill** [comment] 2022-11-26 18:19
@jogibear9988 The suggestion to copy `mscordbi.dll` mentioned in this issue does not work for me. It seems like the bundled runtime in the self-contained published application does not have the required components for debugging or debugging is disabled. By editing the `.runtimeconfig.json` file the runtime is tricked into thinking our application is not self-contained and by editing the `.deps.json` and removing the runtime pack information the bundled runtime is no longer used for execution. This is what allows the debugging of the file.

**Comment by jogibear9988** [comment] 2022-11-27 10:02
Is it possible to attach VisualStudio for debugging?

**Comment by ElektroKill** [comment] 2023-10-14 17:14
Hi, I thought I should probably give an update on this issue. The issue will be fully fixed in the next release since the next release will be running on .NET 8. What does .NET 8 have to do with this? It's the first LTS release after .NET 6 and includes changes from .NET 7. During the lifetime of .NET 7, the library used by dnSpy to initialize CoreCLR debugging, dbgshim.dll, got updated which allows dnSpy to provide additional search paths for the debugging components if they are not included in the current .NET distribution that the process is running under. The issue reported here has to do with certain components of the runtime that are needed for debugging being missing from the self-contained file. By default, dbgshim.dll will only look in the directory of the runtime which will not work for bundles. As mentioned, .NET 7 added a feature to it that allows library consumer to override this search behavior with their custom logic.

I have already implemented code that will detect if the dbgshim.dll being used supports this new feature, and if so overrides the resolution logic with a custom implementation which will first look for the components in the runtime directory, and if it is not found there (for example, self-contained file) it will try to find a matching .NET runtime installation on the current system and use the debugging components from that installation (Note: this requires the exact version of .NET to be installed if the bundle is using 5.0.8, the system needs 5.0.8 installed)

This implementation can be seen here: https://github.com/dnSpyEx/dnSpy/commit/4fe02ebc022fb789f90b4e00932e9b654b60a0f8

Since that commit, the .NET framework distribution also ships with the .NET 7 dbgshim.dll file which allows this improved logic of debugging component resolution to be used. However, the .NET 6 distribution ships with the .NET 6 dbgshim.dll (since the .NET 6 version of dnSpy is shipped as a self-contained app too) which means that it will not use this new behavior. When we move to .NET 8, this issue will be resolved for both distributions. Hopefully, this clarifies the current state of this issue!

**Comment by greenozon** [comment] 2023-10-14 17:36
I'm very pleased to read this update on the raised issue
thanks a lot, great stuff indeed!
Hoping that [.NET 8](https://dotnet.microsoft.com/en-us/download/dotnet/8.0) GA will be released in a little while! 
as for the moment it's RC.2

**Comment by greenozon** [comment] 2023-10-22 10:31
@ElektroKill   could you please shed some light where one could find a build that has your above commit added in?

**Comment by greenozon** [comment] 2023-10-22 10:44
I"m asking cause I'm trying to debug .NET 6.0  assembly 
// Architecture: x64
// Runtime: .NET 6.0

and hitting this error on start:

```
Could not start the debugger. Make sure you have access to the file 'C:\path-to-exe.exe'

Error: Waiting for CoreCLR timed out. Debug 32-bit .NET apps with 32-bit dnSpy (dnSpy-x86.exe), and 64-bit .NET apps with 64-bit dnSpy (dnSpy.exe).

```

tried both .net and framework builds, both lead to same issue as stated above
tried to increase timeout - same result....

**Comment by greenozon** [comment] 2023-10-22 12:16
I've explored more the above case, in reality the .dmp file has been generated in CrashDumps folder
when I open it up it shows this:

![image](https://github.com/dnSpyEx/dnSpy/assets/765343/4173ffcb-1fdf-448f-b43a-78581f6ff144)

so the question is same - is it possible to debug .net 6 app (not bundled, this is different case) in current days using dnSpyEx?

**Comment by ElektroKill** [comment] 2023-10-22 12:19
> I've explored more the above case, in reality the .dmp file has been generated in CrashDumps folder when I open it up it shows this:
> 
> ![image](https://user-images.githubusercontent.com/765343/277163964-4173ffcb-1fdf-448f-b43a-78581f6ff144.png)
> 
> so the question is same - is it possible to debug .net 6 app (not bundled, this is different case) in current days using dnSpyEx?
> 
> PS and yes- I've got .NET 6 SDK on my PC (latest one - 6.0.23) located over here: "c:\Program Files\dotnet\sdk\6.0.415"

Yes, debugging .NET 6 applications should be possible. The error you are experiencing is weird. Would you perhaps be able to provide the file you are working with to me so that I can look further into why dnSpy is unable to attach? You can either upload to github or email me at elektrokilldev@protonmail.com

**Comment by greenozon** [comment] 2023-10-22 12:41
Thanks for quick answer
the app itself is very big... I'll see what could be done

but I"m wondering how these guys from MS are binding newer .net dlls if the app is looking for 6.0.0.0?
this is my dll of above missed dll - 

![image](https://github.com/dnSpyEx/dnSpy/assets/765343/84caa84c-74ca-45b4-9d3b-9157997beb8c)

**Comment by ElektroKill** [comment] 2023-10-22 13:11
> but I"m wondering how these guys from MS are binding newer .net dlls if the app is looking for 6.0.0.0? this is my dll of above missed dll -

.NET does not look at the file properties when looking for assemblies. It looks at the version defined in the assembly metadata which is visible in dnSpy in the treeview or the decompilation of the assembly node.

**Comment by ElektroKill** [comment] 2023-11-02 11:43
@greenozon Sorry for the very late response, the reason your file does not starts i that it is incorrectly renamed to a `.exe` when it should be a `.dll` (.NET core and above uses .dll files which are launched by .exe host files). In this case we are lacking the apphost executable so the way to run it would be using the command line `dotnet {appName}`. However, if we try this, we see that an error is displayed:
![image](https://github.com/dnSpyEx/dnSpy/assets/37494960/3adac2f9-2463-4077-a8fc-91f9f99ec0ab)
This error is present because the file does not have the necessary runtimeconfig file present next to it. This config file is required to run apps outside self-contained environments. Adding this file should fix the problem and allow dnSpy to attach properly. The example content of this file for non-self-contained programs is as follows:
```json
{
  "runtimeOptions": {
    "tfm": "net6.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "6.0.0"
    }
  }
}
```
If this app was self-contained and you obtained the file in question by unpacking the bundle, it is important to convert the app back to its non-self-contained state as described in one of my previous comments. Hope this helps!

**Closed** 2023-11-16 21:31 UTC
Labels: bug, debugger
