### ISSUE TITLE
dnSpy-Unity-mono new version

### ISSUE THREAD

**Issue by t1a2l** [dnSpyEx/dnSpy#39] opened 2021-10-19 23:54 UTC
Hey, I am trying to create dnSpy-Unity-mono for version 2020.3, when using the umpatcher i get an error for copying eglib because it is in mono/mono instead of mono.

ANy help would be appreciated.

**Comment by Soft-me** [comment] 2022-08-10 16:51
> Hey, I am trying to create dnSpy-Unity-mono for version 2020.3, when using the umpatcher i get an error for copying eglib because it is in mono/mono instead of mono.
> 
> ANy help would be appreciated.

Hi , did you fix this problem ? I am trying to do the same thing, and get an error says can't find path "unity-mono\eglib", and I can not find eglib directory in unity-mono which I clone from the latest Unity mono.dll source code. Did I clone the wrong repo?

**Comment by GazziFX** [comment] 2022-08-11 11:52
I think it would be easier to just copy development binaries from Unity
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2552#issuecomment-1025482713

**Comment by ElektroKill** [comment] 2022-09-06 18:05
> @ElektroKill I missing the dnSpy-Unity-mono-v2020.x-V40 solution in the dnspy branch, how can i get it or build it?

@t1a2l Hi, the file you are referencing has been recently added to the `dnSpy` branch in the Unity mono repository. Could you please retry running the patcher as described in the instructions in the readme?

**Comment by ElektroKill** [comment] 2023-02-26 10:32
Closing due to lack of updates. I assume the issue is resolved.

**Closed by ElektroKill** 2023-02-26 10:32 UTC

**Comment by robertschulze** [comment] 2024-01-14 15:18
> I think it would be easier to just copy development binaries from Unity [SmartlyDressedGames/Unturned-3.x-Community#2552 (comment)](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2552#issuecomment-1025482713)

I can confirm this works, followed the instruction [here](https://github.com/dnSpyEx/dnSpy/wiki/Debugging-Unity-Games)
