### ISSUE TITLE
Types taken from System.Private.CoreLib(7.0.0.0) break compilation of projects when dll created by dnSpy is shown as .Net Framework *.* one

### ISSUE THREAD

**Issue by MadProbe** [dnSpyEx/dnSpy#177] opened 2023-03-01 19:45 UTC
I get an error in VS saying "error CS0012: The type 'ReadOnlySpan<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'." from dnSpy-created assembly, when I create an reference to method / class / anything not defined in other referenced assemblies (e.g. mscorlib of .net framework 4.8.1) and is referencing to System.Private.CoreLib(7.0.0.0).
Compilation won't succeed and even if I include the assembly (System.Private.CoreLib) compilation will also fail because of conflicting references (double references to same assembly because System.Private.CoreLib is included automatically)

- What version did you use?
v6.3.0

- Write down all steps needed to reproduce this issue. Also attach any needed files.
1. Create an Assembly in dnSpy.
2. Make a class and a method in it with signature void(System.ReadOnlySpan<int>) where System,ReadOnlySpan comes from System.Private.CoreLib(7.0.0.0) Assembly 
3. Create a C# VS project
4. Add the produced assembly to project's dependencies
5. Try to compile the project, including the call to the method created in the dll earlier with any suitable arguments (doesn't matter actually, can just be default()).

If files needed to be attached, ask me.

**Comment by ElektroKill** [comment] 2023-03-03 18:41
Hi, when creating an assembly meant to target a runtime different than .NET Framework you should always add the `TargetFrameworkAttribute` to the assembly which will specify the target runtime of your file. Please edit the assembly custom attributes and add an instance of that attribute with a valid target framework string as the string parameter. For .NET 7 it is `.NETCoreApp,Version=v7.0`. This will ensure that dnSpy will correctly handle your file when resolving dependencies, decompiling code, and exporting to a project file. It is also vital to ensure that you export your file using the SDK project format as the legacy one is not recommended for modern .NET versions. The format can be changed using one of the settings in the project export dialog.

**Comment by MadProbe** [comment] 2023-03-03 19:26
Thanks for pointing out the need change the `TargetFramework` with the .net 7.0 handle.
Additional info, as I think you didn't fully understood my situation:
I am developing a project which requires handmade IL code, which I do as separate assembly containing code which can't be compiled by Roslyn in normal circumstances (`System,IgnoreAccessChecksAttribute` atribute to ignore access checks and modifying inaccessible fields and calling other assembly's internal functions, direct manipulation with object's memory, etc.).
I have a completely normal VS 2022's c# project with references the dll I made IL code in using dnSpy, and I get the error mentioned by me above

**Comment by ElektroKill** [comment] 2023-03-03 19:59
Okay, I have identified the root cause of this issue. dnSpy is creating references to `System.Private.CoreLib` when in fact it should be generating references pointing to `System.Runtime` which will then forward the types to `System.Private.CoreLib` at runtime. This is the case for pretty much all aspects of the assembly editor component as the UI will not allow you to create references to `System.Runtime` as it defines no real types, only type forwarders. The Edit Class feature also emits incorrect references leading to the issue you are describing.

I will look into possible ways of updating the assembly editor component to improve support for .NET Core and newer runtimes. In the meantime, I can suggest a few alternatives for your use case of emitting IL code that cannot be represented as C#:
* Manually create the assembly using a library like dnlib
* Look into InlineIL.Fody utility which allows you to write inline il in C# methods.

**Comment by ElektroKill** [comment] 2023-03-04 10:23
I've looked into this issue a bit and it seems that it is caused by the fact that dnSpy is feeding the runtime versions of `System.Runtime`, `System.Private.CoreLib`. etc. into Roslyn. For compilation, Roslyn should be provided with the reference assemblies instead of the runtime ones. Please try adding the DLLs located in paths like `dotnet\packs\Microsoft.NETCore.App.Ref\7.0.3\ref\net7.0` as your references instead of the ones from `dotnet\shared\Microsoft.NETCore.App\7.0.3` when adding references in the C# editor/compiler dialog. This should resolve your issue during the first compilation of C# when dnSpy does not provide any references. However, for subsequent ones dnSpy will insist on providing the runtime versions. I'm working on a fix for this behavior.

**Comment by ElektroKill** [comment] 2023-03-04 13:17
In the latest commit, I improved the code responsible for providing the dependency assemblies to Roslyn. It should not provide the proper reference assemblies to the compiler. Although, please note that if you create an assembly from scratch and then use the Add Class option, you should add a reference to the reference assemblies and not the runtime ones in the compiler dialog!

**Comment by ElektroKill** [comment] 2023-03-12 21:12
Closing as fixed due to lack of response.

**Closed by ElektroKill** 2023-03-12 21:12 UTC

**Comment by MadProbe** [comment] 2023-03-13 08:40
Nah, somehow I got it working even in the unfixed version but I don't know how.
