### ISSUE TITLE
Can't Attach Silverlight Plugin In Edge's IE compatibility mode

### ISSUE THREAD

**Issue by baikaishiuc** [dnSpyEx/dnSpy#194] opened 2023-05-06 06:15 UTC
### Description

Hello, I am a beginner in .NET reverse engineering. I launched a Silverlight plugin in Edge's IE compatibility mode, but my dnspy-x86 can see it in the attach window but cannot attach to it and keeps reporting errors. Could you please advise on what might be causing this issue?

![image](https://user-images.githubusercontent.com/618485/236605720-f605de1a-e4d2-4c23-9865-acd102b85c5b.png)

I try dnSpy 5.0.5, 6.1.8, 6.0.3 but they all failed

Should I test with an old version of IE?

**Comment by ElektroKill** [comment] 2023-05-06 09:17
Hi, the error dialog you are seeing means that dnSpy could not retrieve the main debugging interface from the .NET runtime loaded in the target process. This error is almost always caused by the .NET runtime not being fully initialized or being in some special state where the interface cannot be retrieved.

In order to diagnose the issue further, I would need a way to reproduce this error on my system. Without exact steps and all files and configuration necessary to reproduce the issue I cannot tell you any more than that.

Please make sure you have tried using the latest dev build available [here](https://github.com/dnSpyEx/dnSpy/actions?query=branch%3Amaster) too.

**Comment by baikaishiuc** [comment] 2023-05-06 10:22
>> Please make sure you have tried using the latest dev build available [here](https://github.com/dnSpyEx/dnSpy/actions?query=branch%3Amaster) too.
hi, I tried the latest version : 7b8623a, but it stil doesn't work.

>> In order to diagnose the issue further, I would need a way to reproduce this error on my system. Without exact steps and all files and configuration necessary to reproduce the issue I cannot tell you any more than that.

I update a zip file, include all silverlight 
[dnSpyTest.zip](https://github.com/dnSpyEx/dnSpy/files/11412093/dnSpyTest.zip)
app and a README introduce how to reproduce this error.

**Comment by baikaishiuc** [comment] 2023-05-06 16:52
I think Silverlight may be too old for dnSpy to support it.

**Comment by ElektroKill** [comment] 2023-05-06 16:54
Hi, this issue is caused by an incomplete install of the Silverlight .NET runtime. In order for debugging to work on a CoreCLR distribution (Silverlight runs on CoreCLR) two components need to be present next to the `coreclr.dll` binary. These components are the following binaries:
* `mscordbi.dll`
* `mscordaccore.dll`

As documented here: https://learn.microsoft.com/en-us/dotnet/framework/unmanaged-api/debugging/createdebugginginterfacefromversion-function-for-silverlight

When I install Silverlight using the installer you provided on a VM these files are missing from the installation and when dnSpy calls the `CreateDebuggingInterfaceFromVersion` function it fails to create the debugging interface.

On an interesting note, on my main PC I have an older Silverlight version installed which looks to be more complete and includes more parts of the CoreCLR used for instrumentation and debugging. When testing on this installation of Silverlight, dnSpy is able to attach successfully.

I think this issue is caused by a tampered-with or incomplete installer of Silverlight. Or perhaps Microsoft removed the debugging components from some distributions of SIlverlight?

**Comment by ElektroKill** [comment] 2023-05-06 16:58
Upon further investigation, these are all the DLL files missing in the installation on my VM (using the installer you provided) versus the installation on my main PC installed ages ago:
* `agcore.debug.dll`
* `dbgshim.dll`
* `mscordaccore.dll`
* `mscordbi.dll`
* `mscorrc.debug.dll`
* `sos.dll`

All of these files are related to the debugging of the CoreCLR runtime.

**Comment by ElektroKill** [comment] 2023-05-06 20:34
Due to this being out of scope for dnSpyEx (missing runtime components are not something dnSpy can fix), I will go ahead and close the issue now. If you still belive there is something that could be changed in regard to this problem, feel free to comment on the issue.

**Closed by ElektroKill** 2023-05-06 20:34 UTC
Labels: debugger

**Comment by baikaishiuc** [comment] 2023-05-07 00:55
Thank you very much for your detailed reply, which greatly enhances my understanding of .net debugging mode. I have spent a long time here.

I would like to make a donation, but I do not have a US credit card, only Alipay (I am in China).

**Comment by ElektroKill** [comment] 2023-05-07 07:26
> I would like to make a donation, but I do not have a US credit card, only Alipay (I am in China).

Please contact me via email or discord to discuss alternatives!
