### ISSUE TITLE
File 'dnSpy-Unity-mono-v2020.x-V40' doesn't exist

### ISSUE THREAD

**Issue by Soft-me** [dnSpyEx/dnSpy#123] opened 2022-08-12 05:33 UTC
hmm , I try to use dnSpy-Unity-mono to build `mono-2.0-bdwgc.dll` for a new Unity version 2020.2.2 .

So I follow all steps in [Supporting a new Unity version for Dummies](https://github.com/dnSpyEx/dnSpy-Unity-mono#supporting-a-new-unity-version-for-dummies).
In the last step: 
Run umpatcher again to patch the code and commit it to the dnSpy-Unity-mono repo
  - `umpatcher 5.4.3 aa8a6e7afc2f4fe63921df4fe8a18cfd0a441d19 "C:\path\to\Unity-mono" "C:\path\to\dnSpy-Unity-mono"`

And I get error: "File 'dnSpy-Unity-mono-v2020.x-V40' doesn't exist"
I have to say I am a totally newbie for these things. Do I miss something or I completely do it in the wrong way?

**Comment by ElektroKill** [comment] 2022-08-12 08:40
Note: copy of the response from discussion https://github.com/dnSpyEx/dnSpy/discussions/124

Hi, this is not entirely an error on your side. The dnSpy unity mono patcher doesn't yet officially support unity versions past 2019. The patcher requires a VS solution to be present for every major Unity version, in this case 2020. This file does not exist in the repository yet as there haven't been any unity versions added with that major version number. An error you are making is specifying the incorrect version of Unity to the umpatcher program. The first argument specifies the version of Unity that you are currently trying to patch, this is not the reason for the error though. I will look into adding the necessary files for supporting newer major versions of Unity in the coming days.

**Comment by ElektroKill** [comment] 2022-08-31 12:58
I have added the solution files in the following commit: https://github.com/dnSpyEx/dnSpy-Unity-mono/commit/15ab946e9706a0f6b231ce6ec27b936f8b7b368f
Please pull the latest changes to the `dnSpy` branch and retry patching. If further issues arise, please let me know!

**Comment by Soft-me** [comment] 2022-09-01 02:07
Same as last time.
![Snipaste_2022-09-01_10-03-44](https://user-images.githubusercontent.com/35207058/187816930-d1e31893-cf2d-40a2-b9ee-8cb4320c2abc.png)

**Comment by ElektroKill** [comment] 2022-09-01 11:11
The error you are getting now indicates that the execution of 'git commit' by the `umpatcher` tool failed. The previous error referred to the `dnSpy-Unity-mono-v2020.x-V40` file not existing. The new error may be caused by other unstaged changes in your local repository or a different circumstance not expected by the `umpatcher` tool. Please try patching this new unity mono version from scratch, as well as recloning `dnSpy-Unity-Mono`. If that doesn't work please let me know!

**Comment by zindarato** [comment] 2022-10-31 04:50
@ElektroKill I ran into the same issue here. It appears there's a merge conflict between the existing versions of the dnSpy and master branches. Even running a merge between those branches (master merging into dnSpy) locally with no changes, there are still conflicts that need to be resolved before the merge can complete. Since we're doing the merge as part of the umpatcher, the umpatcher program fails to finish.

I was able to get this working in my own environment, but only by heavily adjusting the behavior of the umpatcher program. I had to remove all checks for unmodified source state, and in addition had to run through the file processing steps on a wrong branch, since the normal process of making changes in master, switching to dnSpy, then merging into dnSpy would no longer work. After removing those safety checks, though, things did work as expected and I have a functional mono-2 dll that is working with my games.

Figured you'd want to know, since it sounds like this could cause problems for anyone using umpatcher.

Thanks!

**Comment by ElektroKill** [comment] 2022-11-05 13:22
@zindarato Thanks a lot for this info, I have already identified the reason as to how the merge conflict came into existence. I will work on resolving it soon so that the unity mono patching can be performed again :p

**Comment by zindarato** [comment] 2022-11-05 17:34
@ElektroKill Great, thanks very much! And thank you for building such a useful piece of software, its made a couple of projects much easier for me.

**Comment by sunnamed434** [comment] 2022-11-05 17:37
There is another way how to debug in dnspy, actually Im not sure would you even want to debug smth, but probably this info could be useful for someone, [read here](https://github.com/dnSpyEx/dnSpy/issues/39#issuecomment-1211885152)

**Comment by ElektroKill** [comment] 2023-02-26 10:28
The issues with the missing solution file and the merge error should be fixed now!

**Closed by ElektroKill** 2023-02-26 10:28 UTC
