### ISSUE TITLE
since 6.2.0-rc1 netstandard 2.1 instead of 2.0 gets imported

### ISSUE THREAD

**Issue by cocoon** [dnSpyEx/dnSpy#191] opened 2023-04-27 09:55 UTC
### dnSpyEx version

6.2.0-rc1 up to current

### Describe the Bug

I found a changed behavior from 6.1.9 to 6.2.0-rc1 (up to current version) when I open the Github "Octokit.dll"

In v6.1.9 it correctly automatically opens netstandard 2.0 and mscorlib 4.
Since 6.2.0-rc1 it instead opens netstandard 2.1.0.0 and System.Private.CoreLib 7

This causes that if I do my changes and add a readonly list to fix a problem, it will later fail to load in the final program, as it cannot find System.Private.CoreLib because it is a Framework app.

### How To Reproduce

The file can be downloaded from here, extract and in lib: 
https://www.nuget.org/api/v2/package/Octokit/4.0.0

simply open the Octokit.dll

### Expected Behavior

it automatically opens netstandard 2.0 and mscorlib 4

### Actual Behavior

it opens netstandard 2.1.0.0 and System.Private.CoreLib 7

### Additional Context

![v6 1 9](https://user-images.githubusercontent.com/1071741/234828033-531ea53b-7678-49d0-9962-bb34ee8dfa1e.png)

![v6 2 0-rc1](https://user-images.githubusercontent.com/1071741/234828040-401e4827-828d-46e6-9a2b-57f239a7ade4.png)

**Comment by ElektroKill** [comment] 2023-05-05 10:42
Hi, dnSpyEx resolves .NET Standard references to assemblies from .NET Core installation directories since .NET Framework does not support all .NET Standard versions. What you see is a bug leading to the incorrect version being resolved. I will introduce a fix that will change the assembly resolution algorithm to search for a netstandard in the .NET Core installation directories which most closely matches the referenced version and if a version like that cannot be found, fallback to the .NET Framework GAC version.

This would mean that for .NET Standard oldethanen 2.0, dnSpy would try to locate a .NET Core installation oldethanen 2.0 on the system and use the .NET standard binary from there. For .NET Standard 2.0, it would search for a .NET Core installation older than 3.0, and for .NET Standard 2.1 or newer, it would use the latest .NET Core installation available. If the .NET Core installation dnSpy is searching for cannot be found, it will fall back to .NET Framework GAC netstandard dll.

This new approach will allow for better accuracy when resolving assemblies.

I know the expected behavior you mentioned is always resolving to the .NET Framework netsatndard 2.0, however, I think that this is not always the best choice as mentioned above. .NET Standard resolution, in general, is a bit tricky to do in a intuitive way as there are multiple sources to fetch the DLLs from.

**Comment by cocoon** [comment] 2023-05-05 12:12
Thank you very much for the details! Yes it not easy.

I just tried the new build and it behaves a bit different for me, but still adds a reference to Corelib.

I don't know if the references of the opened DLL could be checked additionally, in the case of Octokit.dll it only has a reference to netstandard and nothing else. 

After editing it with the new build it now still adds a reference (see screenshots).


![1](https://user-images.githubusercontent.com/1071741/236454479-668cb8b8-2f90-4bcb-a7ef-637b7853291c.png)

![2](https://user-images.githubusercontent.com/1071741/236454482-ab04e3e0-7685-4997-88c8-b60698d5fb4e.png)

**Comment by ElektroKill** [comment] 2023-05-05 12:41
Hi, this is because dnSpy does not currently properly locate the reference assemblies for .NET standard versions before 2.1. This is because they are not installed in the same location as .NET Core reference assemblies. The Edit Code (C#) feature needs reference assemblies for .NET Core or .NET Standard to generate proper references. If these reference assemblies cannot be found, dnSpy will fall back to runtime assemblies which are structured differently and result in the additional reference to `System.Private.CoreLib`. This is what we see happening in this case. Locating .NET Standard 2.0 reference assemblies will be tricky as last time I checked they are usually obtained via NuGet and not installed via an SDK package. This makes locating them a bit harder as it would require dnSpy to locate the NuGet package cache on the system which may prove to be a bit tricky. It seems I will have to look into this sooner than I initially thought.

**Comment by cocoon** [comment] 2023-05-05 12:44
Sound interesting.


Just some more details:

v6.1.9 adds it from this Path in my case:
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.30\mscorlib.dll

vNext adds it from the same path but System.Private.CoreLib.dll

**Comment by ElektroKill** [comment] 2023-05-08 20:18
Hi, I implemented logic to locate .NET Standard 2.0 and earlier reference assemblies from local NuGet package sources and the global NuGet package cache. Could you please give it a go and see if it solves your issue and let me know of the results?

A build including this fix is available here (still building at the time of writing): https://github.com/dnSpyEx/dnSpy/actions/runs/4919236873

**Comment by cocoon** [comment] 2023-05-09 15:29
Just again the detailed easy steps with the previous version from 5th of May to reproduce old problem:

- Open Okctokit.dll 
- "Edit Method" on "GetAllLicenses(ApiOptions options)"
- return an empty readonly list
`return Task.FromResult<IReadOnlyList<LicenseMetadata>>(new List<LicenseMetadata>().AsReadOnly());`

- File -> Save Module ...
- Open newly saved file and see added reference



![000](https://github.com/dnSpyEx/dnSpy/assets/1071741/bf1af06c-a1c1-4f25-b33e-93cfdb42e46b)
![001](https://github.com/dnSpyEx/dnSpy/assets/1071741/d7e6037a-1784-44b2-bd55-aa0d3fb63bdf)

![002](https://github.com/dnSpyEx/dnSpy/assets/1071741/2805b33e-c0af-4ad5-b27c-1fa448d8989d)
![003](https://github.com/dnSpyEx/dnSpy/assets/1071741/100842de-c208-417d-a38a-48dc2c77f9c4)

**Comment by ElektroKill** [comment] 2023-05-09 15:39
> It still automatically "opens" System.Private.CoreLib:

This is the intended behavior, when exploring the assembly, decompiling, and debugging dnSpy loads the runtime versions of the assemblies. The runtime version of the `netstandard` assembly is just a dummy assembly which forwards all type resolutions to `System.Private.CoreLib`.

> BUT when I now edit the file manually and return some readonly lists it now doesn't add any new reference and it only keeps the existing netstandard reference!

I updated the Edit Code component to load the correct reference/compile-time assembly for .NET Standard 2.0 from NuGet package cache stored on the disk.

> GOOD WORK! Works perfectly for me!
 Good to hear that! Please close the issue if you believe it is resolved :p

**Closed** 2023-05-10 12:38 UTC
Labels: bug
